# helmfile.d/values/common.yaml
---
# Valores base compartidos

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage:
    size: 1Gi