---
# Configuración base compartida

# Global
baseDomain: example.com

# PostgreSQL
postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  port: 5432
  persistence:
    enabled: false
    size: 1Gi
    className: standard
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# App Service
appService:
  enabled: true
  image:
    repository: nginx  # Placeholder - cambiar al buildear imagen
    tag: alpine
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  ingress:
    enabled: false

# Ingress (opcional)
ingressNginx:
  enabled: false  # Deshabilitado por defecto