---
postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  port: 5432
  databases:
    - appdb
  password: "pass-default" 
  persistence:
    enabled: false
    size: 1Gi
    className: standard
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
